FROM registry.fedoraproject.org/fedora:44

RUN dnf install -y \
        make gcc gcc-c++ gcc-gfortran gawk autoconf automake git rust cargo cmake \
        zlib-devel libffi-devel openssl-devel bzip2-devel \
        readline-devel sqlite-devel xz-devel \
        flexiblas-devel flexiblas-openblas-openmp pkgconf-pkg-config libyaml-devel \
    && dnf clean all \
    && ln -s flexiblas.pc /usr/lib64/pkgconfig/openblas.pc

COPY ci/cargo-config.toml /opt/cargo/config.toml
ENV CARGO_HOME=/opt/cargo

WORKDIR /src
